#+BEGIN_COMMENT
.. title: Hello, world!
.. slug: hello-world
.. date: 12-21-2013
.. tags: blog, 
.. link:
.. description: The start of a new site
.. type: text
#+END_COMMENT

#+OPTIONS: toc:nil

Well, I've finally got this site off the ground... more or less.

This website is the continuation of my blog, [[http://quadrule.blogspot.com][My Quad-Ruled Life]]. On
that site, I explored a number of topics as a graduate student in
optics, while improving my writing as well. As the site progressed
and I matured academically, I found that I was blogging less often,
but still used the blog as a means of exploring ideas. Additionally,
I desired a place to present notes and code to the public in an
easily accessible and open manner.

So, after discovering [[http://getnikola.com/][Nikola]] and [[http://pages.github.com/][GitHub Pages]], I quickly hashed
together a fully homemade site that allowed me to keep writing blog
posts and to present some of the fruits of my research freely on the
internet.

I hope you'll find this site useful as a learning resource and as a
means to get to know me better as a scientist.

-Kyle
