#+BEGIN_COMMENT
.. title: Android Notes
.. slug: android
.. date: 08/19/2017
.. tags: 
.. link: android, linux
.. description: Notes on Android development
.. type: text
#+END_COMMENT
#+OPTIONS: toc:nil num:t ^:nil
#+TOC: headlines 2

* Android Development Setup

These instructions are for Linux operating systems.

1. Download the Android SDK from
   https://developer.android.com/studio/index.html.
2. Unzip the file.
3. Run the script android-studio/bin/studio.sh and follow the
   directions.
4. Add *~/Android/Sdk/platform-tools* to your shell path to use the
   programs.

-----

* Common ADB Commands

*Date: August 19, 2017*

*Source: https://www.androidcentral.com/android-201-10-basic-terminal-commands-you-should-know*

- adb devices :: List the devices connected to the computer. (The
                 Android device must be in USB debugging mode.)
- adb push :: Push data onto the Android device. =adb push
              path/to/pc/file android/path=
- adb pull :: Pull data from the Android device. =adb pull
              path/to/android/file pc/path=
- adb reboot :: Restarts the device.
- adb shell :: Enter a shell on the Android device.

-----

* Setup Android to use a static IP

*Date: August 19, 2017*

*Source:
http://www.techrepublic.com/article/how-to-set-a-static-ip-address-on-android/*

I've tested this on for Android 7.0.

1. Navigate to Settings > Wi-Fi.
2. Longpress on the desired network.
3. Select *Modify network*.
4. Expand *Advanced options*.
5. Select *Static* from *IP settings*.
6. Enter the static IP and gateway.
7. For network prefix length, take the network gateway address,
   convert it to binary, then count the number of leading 1's. For
   example, 255.255.255.0 is 11111111 11111111 11111111 00000000 in
   binary, and there are 24 1's. The network prefix length is
   therefore 24.
8. Save your settings. I needed to restart the Wi-Fi on my device to
   log on to the network.
