#+BEGIN_COMMENT
.. title: Nikola
.. slug: nikola
.. date: 12/26/2014
.. tags: nikola
.. link:
.. description: How to setup Nikola for making static websites
.. type: text
#+END_COMMENT

* First steps

** Initialize the site
   Type the following at the command line to initialize a new Nikola
   site:

   #+BEGIN_SRC sh
nikola init site_name
   #+END_SRC

   Answer the questions to setup the initial site. Be sure the base
   URL ends in '/'.

-----

** Set the theme to oldfashioned with a color scheme from bootswatch
   First, install the olfashioned theme from the themes repository.

   #+BEGIN_SRC sh
nikola install_theme oldfashioned
   #+END_SRC

   Next, change the color scheme to slate from bootswatch.com.

   #+BEGIN_SRC sh
nikola bootswatch_theme -n custom_theme -s slate -p oldfashioned
   #+END_SRC
   
   Finally, change the theme variable to /custom_theme/ inside
   conf.py.

-----

** Install and configure the org-mode plugin
   Nikola can compile org-mode files using a custom
   plugin. Information on the plugin can be found here:
   http://plugins.getnikola.com/#orgmode. To install the plugin for my
   site, I ran the following command from inside my site directory:

   #+BEGIN_SRC sh
nikola plugin -i orgmode
   #+END_SRC

   This created a folder called /plugins/ inside the site directory
   containing the orgmode plugin files. The most important file is
   init.el.

   Next, I had to add the org-mode compiler to the COMPILERS
   dictionary in conf.py:

   #+BEGIN_SRC python
COMPILERS["orgmode"] = ('.org',)
   #+END_SRC
   
   Note that I manually edited the COMPILERS dictionary to add the
   key-value pair; I did not actually add to the dictionary with the
   code above. 
   
   I also had to modify my POSTS and PAGES variables in
   conf.py to read .org files:

   #+BEGIN_SRC python
POSTS = POSTS + (("posts/*.org", "posts", "post.tmpl"),)
PAGES = PAGES + (("stories/*.org", "posts", "post.tmpl"),)
   #+END_SRC

   To create a post using org-mode, I need to enter the following code
   at the top of the org-file in a comments section:
   
   #+BEGIN_SRC
#+BEGIN_COMMENT
.. title:
.. slug: 
.. date: 
.. tags: 
.. link:
.. description:
.. type: text
#+END_COMMENT
   #+END_SRC

-----

** Setting the github\_deploy variables

   When publishing a project website on GitHub, you push the website
   files to a branch called *gh-pages*. However, when publishing a
   GitHub user page, the files are pushed to the *master* branch.

   By default, Nikola is configured to push to gh-pages. For my
   personal website, I need to change the deploy branch to master. I
   can do this in the conf.py file by uncommenting and modifying the
   line for the GITHUB\_DEPLOY\_BRANCH variable:

   #+BEGIN_SRC python
GITHUB_DEPLOY_BRANCH = 'master'
   #+END_SRC

-----

* Customization

** Navigation links
   You can edit what navigation links appear by changing the
   NAVIGATION LINKS variable in conf.py. See this section of the
   handbook: http://getnikola.com/handbook.html#configuration

   

