#+BEGIN_COMMENT
.. title: Notes and Projects
.. slug: notes-and-projects
.. date: 12-26-2014
.. tags: 
.. link:
.. description: Notes on my various projects
.. type: text
#+END_COMMENT

* pgFocus autofocus module
  I've tested Karl Bellve's [[http://big.umassmed.edu/wiki/index.php/PgFocus][pgFocus]] open source and open hardware
  autofocus module. This module maintains the focus of a microscope
  overtime by sending a control signal that adjusts the position of
  the microscope objective. The control signal is generated in
  response to the displacement of an infrared beam hitting a linear
  light sensor array. The beam is reflected off of the coverslip/water
  interface.
  
  + [[file:notes/pgFocus.org][Notes on pgFocus]]
  + [[http://big.umassmed.edu/wiki/index.php/PgFocus][Karl Bellve's pgFocus Wiki]]

  -----

* Setting up OMERO
  These are my notes on setting up the OMERO client-server software
  for microscopy data.

  + [[file:notes/omero.org][Notes on OMERO]]
  + [[http://www.openmicroscopy.org/site][The Open Microscopy Environment website]]
  
  -----

* Micro-Manager
  Using and customizing Micro-Manager takes a while to learn. Here are
  the notes I have collected along the way.

  + [[file:notes/micro-manager.org][Micro-Manager notes]]
  + [[https://www.micro-manager.org/][The Micro-Manager website]]

  -----

* Computer notes
  These are all the notes I've collected so far for getting things
  done on computers. I hope they can help you as well.

  + [[file:notes/linux.org][Notes on Linux]]
  + [[file:notes/scipy.org][Python for Scientific Applications]]
  + [[file:notes/emacs.org][Emacs]]
  + [[file:notes/git.org][Git]]
  + [[file:notes/nikola.org][Nikola]]
  + [[file:notes/windows.org][Notes on Windows]]
